version: "3"
services:
  redis:
    container_name: "redis_app"
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - "./developer/redis :/data"

  postgres:
    container_name: "postgres_app"
    image: postgres:12
    environment:
      POSTGRES_DB: "apppib"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
    tty: true
    stdin_open: true
